version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - durationcheck
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
          - revive
          - staticcheck
          - unused
        path: 'internal/linkname/(.+).go'
      - linters:
          - govet
          - nolintlint
          - predeclared
          - revive
          - staticcheck
          - unparam
          - unused
        path: 'unsafe/(.+)\.go'
      - linters:
          - errcheck
          - funlen
          - goconst
          - ineffassign
          - revive
          - staticcheck
          - unparam
          - unused
          - whitespace
        path: '(.+)_test\.go'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/jxskiss/gopkg)
    goimports:
      local-prefixes:
        - github.com/jxskiss/gopkg
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
