// Code generated by go generate at 2020-03-04T14:48:24+08:00; DO NOT EDIT.

package set

import "encoding/json"

// Int is int set collection.
// The zero value of Int is an empty instance ready to use. A zero Int
// value shall not be copied, or it may result incorrect behavior.
type Int struct {
	m map[int]struct{}
}

// NewInt creates Int instance.
func NewInt(vals ...int) Int {
	size := max(len(vals), minSize)
	set := Int{
		m: make(map[int]struct{}, size),
	}
	set.Add(vals...)
	return set
}

// NewIntWithSize creates Int instance with given initial size.
func NewIntWithSize(size int) Int {
	set := Int{
		m: make(map[int]struct{}, size),
	}
	return set
}

// Size returns the size of set.
func (s *Int) Size() int { return len(s.m) }

// Add adds values into the set.
func (s *Int) Add(vals ...int) {
	if s.m == nil {
		size := max(len(vals), minSize)
		s.m = make(map[int]struct{}, size)
	}
	for idx := range vals {
		s.m[vals[idx]] = struct{}{}
	}
}

// Del deletes values from the set.
func (s *Int) Del(vals ...int) {
	for idx := range vals {
		delete(s.m, vals[idx])
	}
}

// Pop pops an element from the set, in no particular order.
func (s *Int) Pop() int {
	for val := range s.m {
		delete(s.m, val)
		return val
	}
	return 0
}

// Iterate iterates the set in no particular order and call the given function
// for each set element.
func (s *Int) Iterate(fn func(int)) {
	for val := range s.m {
		fn(val)
	}
}

// Contains returns true if the set contains all the values.
func (s *Int) Contains(vals ...int) bool {
	if len(vals) == 0 {
		return false
	}
	for _, v := range vals {
		if _, ok := s.m[v]; !ok {
			return false
		}
	}
	return true
}

// ContainsAny returns true if the set contains any of the values.
func (s *Int) ContainsAny(vals ...int) bool {
	for _, v := range vals {
		if _, ok := s.m[v]; ok {
			return true
		}
	}
	return false
}

// Diff returns new Int about the values which other set doesn't contain.
func (s Int) Diff(other Int) Int {
	res := NewIntWithSize(s.Size())

	for val := range s.m {
		if _, ok := other.m[val]; !ok {
			res.m[val] = struct{}{}
		}
	}
	return res
}

// DiffSlice is similar to Diff, but takes a slice as parameter.
func (s Int) DiffSlice(other []int) Int {
	if len(s.m) > len(other) {
		tmp := NewIntWithSize(len(other))
		dup := 0
		for _, val := range other {
			if _, ok := s.m[val]; ok {
				dup++
			}
			tmp.m[val] = struct{}{}
		}
		res := NewIntWithSize(max(s.Size()-dup, 0))
		for val := range s.m {
			if _, ok := tmp.m[val]; !ok {
				res.m[val] = struct{}{}
			}
		}
		return res
	} else {
		res := NewIntWithSize(s.Size())
		for val := range s.m {
			res.m[val] = struct{}{}
		}
		for _, val := range other {
			if _, ok := res.m[val]; ok {
				delete(res.m, val)
			}
		}
		return res
	}
}

// FilterInclude returns a new slice which contains values that present in
// the provided slice and also present in the Int set.
func (s Int) FilterInclude(slice []int) []int {
	res := make([]int, 0, min(s.Size(), len(slice)))
	for _, val := range slice {
		if _, ok := s.m[val]; ok {
			res = append(res, val)
		}
	}
	return res
}

// FilterExclude returns a new slice which contains values that present in
// the provided slice but don't present in the Int set.
func (s Int) FilterExclude(slice []int) []int {
	res := make([]int, 0, len(slice))
	for _, val := range slice {
		if _, ok := s.m[val]; !ok {
			res = append(res, val)
		}
	}
	return res
}

// Intersect returns new Int about values which other set also contains.
func (s Int) Intersect(other Int) Int {
	res := NewIntWithSize(min(s.Size(), other.Size()))

	// loop over the smaller set
	if len(s.m) <= len(other.m) {
		for val := range s.m {
			if _, ok := other.m[val]; ok {
				res.m[val] = struct{}{}
			}
		}
	} else {
		for val := range other.m {
			if _, ok := s.m[val]; ok {
				res.m[val] = struct{}{}
			}
		}
	}
	return res
}

// IntersectSlice is similar to Intersect, but takes a slice as parameter.
func (s Int) IntersectSlice(other []int) Int {
	res := NewIntWithSize(min(s.Size(), len(other)))

	for _, val := range other {
		if _, ok := s.m[val]; ok {
			res.m[val] = struct{}{}
		}
	}
	return res
}

// Union returns new Int about values either in the set or the other set.
func (s Int) Union(other Int) Int {
	res := NewIntWithSize(s.Size() + other.Size())

	for val := range s.m {
		res.m[val] = struct{}{}
	}
	for val := range other.m {
		res.m[val] = struct{}{}
	}
	return res
}

// UnionSlice is similar to Union, but takes a slice as parameter.
func (s Int) UnionSlice(other []int) Int {
	res := NewIntWithSize(s.Size() + len(other))

	for val := range s.m {
		res.m[val] = struct{}{}
	}
	for _, val := range other {
		res.m[val] = struct{}{}
	}
	return res
}

// Slice converts set into int slice.
func (s Int) Slice() []int {
	res := make([]int, 0, len(s.m))

	for val := range s.m {
		res = append(res, val)
	}
	return res
}

// Map converts set into map[int]bool.
func (s Int) Map() map[int]bool {
	res := make(map[int]bool, len(s.m))

	for val := range s.m {
		res[val] = true
	}
	return res
}

// MarshalJSON implements json.Marshaler interface, the set will be
// marshaled as an int array.
func (s Int) MarshalJSON() ([]byte, error) {
	res := s.Slice()
	return json.Marshal(res)
}

// UnmarshalJSON implements json.Unmarshaler interface, it will unmarshal
// an int array to the set.
func (s *Int) UnmarshalJSON(b []byte) error {
	vals := make([]int, 0)
	err := json.Unmarshal(b, &vals)
	if err == nil {
		s.Add(vals...)
	}
	return err
}

// MarshalYAML implements yaml.Marshaler interface of the yaml package,
// the set will be marshaled as an int array.
func (s Int) MarshalYAML() (interface{}, error) {
	res := s.Slice()
	return res, nil
}

// UnmarshalYAML implements yaml.Unmarshaler interface of the yaml package,
// it will unmarshal an int array to the set.
func (s *Int) UnmarshalYAML(unmarshal func(interface{}) error) error {
	vals := make([]int, 0)
	err := unmarshal(&vals)
	if err == nil {
		s.Add(vals...)
	}
	return err
}
