// Code generated by go generate at 2019-10-17T13:51:53+08:00; DO NOT EDIT.

package set

import "encoding/json"

// Int is int set collection.
type Int struct {
	m map[int]struct{}
}

// NewInt creates Int instance.
func NewInt(vals ...int) *Int {
	set := &Int{
		m: make(map[int]struct{}),
	}
	set.Add(vals...)
	return set
}

// Add adds values into the set.
func (s *Int) Add(vals ...int) {
	for idx := range vals {
		s.m[vals[idx]] = struct{}{}
	}
}

// Del deletes values from the set.
func (s *Int) Del(vals ...int) {
	for idx := range vals {
		delete(s.m, vals[idx])
	}
}

// Pop pops an element from the set, in no particular order.
func (s *Int) Pop() int {
	for val := range s.m {
		delete(s.m, val)
		return val
	}
	return 0
}

// Iterate iterates the set in no particular order and call the given function
// for each set element.
func (s *Int) Iterate(fn func(int)) {
	for val := range s.m {
		fn(val)
	}
}

// Contains returns true if the set contains all the values.
func (s *Int) Contains(vals ...int) bool {
	if len(vals) == 0 {
		return false
	}
	for _, v := range vals {
		if _, ok := s.m[v]; !ok {
			return false
		}
	}
	return true
}

// ContainsAny returns true if the set contains any of the values.
func (s *Int) ContainsAny(vals ...int) bool {
	for _, v := range vals {
		if _, ok := s.m[v]; ok {
			return true
		}
	}
	return false
}

// Diff returns new Int about the values which other set doesn't contain.
func (s *Int) Diff(other *Int) *Int {
	res := NewInt()

	for val := range s.m {
		if !other.Contains(val) {
			res.Add(val)
		}
	}
	return res
}

// Intersect returns new Int about values which other set also contains.
func (s *Int) Intersect(other *Int) *Int {
	res := NewInt()

	// loop over the smaller set
	if len(s.m) <= len(other.m) {
		for val := range s.m {
			if other.Contains(val) {
				res.Add(val)
			}
		}
	} else {
		for val := range other.m {
			if s.Contains(val) {
				res.Add(val)
			}
		}
	}
	return res
}

// Union returns new Int about values either in the set or the other set.
func (s *Int) Union(other *Int) *Int {
	res := NewInt()

	for val := range s.m {
		res.Add(val)
	}
	for val := range other.m {
		res.Add(val)
	}
	return res
}

// Size returns the size of set.
func (s *Int) Size() int {
	return len(s.m)
}

// Slice converts set into int slice.
func (s *Int) Slice() []int {
	res := make([]int, 0, len(s.m))

	for val := range s.m {
		res = append(res, val)
	}
	return res
}

// Map converts set into map[int]bool.
func (s *Int) Map() map[int]bool {
	res := make(map[int]bool, len(s.m))

	for val := range s.m {
		res[val] = true
	}
	return res
}

// MarshalJSON implements json.Marshaler interface, the set will be
// marshaled as an int array.
func (s *Int) MarshalJSON() ([]byte, error) {
	res := s.Slice()
	return json.Marshal(res)
}

// UnmarshalJSON implements json.Unmarshaler interface, it will unmarshal
// an int array to the set.
func (s *Int) UnmarshalJSON(b []byte) error {
	vals := make([]int, 0)
	err := json.Unmarshal(b, &vals)
	if err == nil {
		s.Add(vals...)
	}
	return err
}
